include("e2fsprogs.cmake")
set(target ext2fs)
set(target_dir "${CMAKE_SOURCE_DIR}/platform/external/e2fsprogs/lib/ext2fs")

set(target_srcs
        "${target_dir}/ext2_err.c"
        "${target_dir}/alloc.c"
        "${target_dir}/alloc_sb.c"
        "${target_dir}/alloc_stats.c"
        "${target_dir}/alloc_tables.c"
        "${target_dir}/atexit.c"
        "${target_dir}/badblocks.c"
        "${target_dir}/bb_inode.c"
        "${target_dir}/bitmaps.c"
        "${target_dir}/bitops.c"
        "${target_dir}/blkmap64_ba.c"
        "${target_dir}/blkmap64_rb.c"
        "${target_dir}/blknum.c"
        "${target_dir}/block.c"
        "${target_dir}/bmap.c"
        "${target_dir}/check_desc.c"
        "${target_dir}/crc16.c"
        "${target_dir}/crc32c.c"
        "${target_dir}/csum.c"
        "${target_dir}/closefs.c"
        "${target_dir}/dblist.c"
        "${target_dir}/dblist_dir.c"
        "${target_dir}/digest_encode.c"
        "${target_dir}/dirblock.c"
        "${target_dir}/dirhash.c"
        "${target_dir}/dir_iterate.c"
        "${target_dir}/dupfs.c"
        "${target_dir}/expanddir.c"
        "${target_dir}/ext_attr.c"
        "${target_dir}/extent.c"
        "${target_dir}/fallocate.c"
        "${target_dir}/fileio.c"
        "${target_dir}/finddev.c"
        "${target_dir}/flushb.c"
        "${target_dir}/freefs.c"
        "${target_dir}/gen_bitmap.c"
        "${target_dir}/gen_bitmap64.c"
        "${target_dir}/get_num_dirs.c"
        "${target_dir}/get_pathname.c"
        "${target_dir}/getenv.c"
        "${target_dir}/getsectsize.c"
        "${target_dir}/getsize.c"
        "${target_dir}/hashmap.c"
        "${target_dir}/i_block.c"
        "${target_dir}/icount.c"
        "${target_dir}/imager.c"
        "${target_dir}/ind_block.c"
        "${target_dir}/initialize.c"
        "${target_dir}/inline.c"
        "${target_dir}/inline_data.c"
        "${target_dir}/inode.c"
        "${target_dir}/io_manager.c"
        "${target_dir}/ismounted.c"
        "${target_dir}/link.c"
        "${target_dir}/llseek.c"
        "${target_dir}/lookup.c"
        "${target_dir}/mmp.c"
        "${target_dir}/mkdir.c"
        "${target_dir}/mkjournal.c"
        "${target_dir}/namei.c"
        "${target_dir}/native.c"
        "${target_dir}/newdir.c"
        "${target_dir}/nls_utf8.c"
        "${target_dir}/openfs.c"
        "${target_dir}/orphan.c"
        "${target_dir}/progress.c"
        "${target_dir}/punch.c"
        "${target_dir}/qcow2.c"
        "${target_dir}/rbtree.c"
        "${target_dir}/read_bb.c"
        "${target_dir}/read_bb_file.c"
        "${target_dir}/res_gdt.c"
        "${target_dir}/rw_bitmaps.c"
        "${target_dir}/sha256.c"
        "${target_dir}/sha512.c"
        "${target_dir}/swapfs.c"
        "${target_dir}/symlink.c"
        "${target_dir}/undo_io.c"
        #"${target_dir}/unix_io.c"
        "${target_dir}/sparse_io.c"
        "${target_dir}/unlink.c"
        "${target_dir}/valid_blk.c"
        "${target_dir}/version.c"
        # get rid of this?!
        "${target_dir}/test_io.c"
)

if(WIN32)
    list(APPEND target_srcs "${target_dir}/windows_io.c")
else()
    list(APPEND target_srcs "${target_dir}/unix_io.c")
endif()

add_library(${target} ${target_srcs})
target_compile_options(${target} PRIVATE ${e2fsprogs_default_cflags})
target_include_directories(${target} PUBLIC ${libext2_headers} ${target_dir})
target_link_libraries(${target} PRIVATE ext2_com_err sparse zlibstatic)